version: '3.8'

services:
  web:
    build: 
      context: .
      target: development  # Use "production" for production builds
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - NAME=World
    command: gunicorn --bind 0.0.0.0:8000 flask_async_api:app

  celery_worker:
    build: 
      context: .
      target: development  # Use "production" for production builds
    volumes:
      - .:/code
    environment:
      - NAME=World
    command: celery -A tasks.celery worker --loglevel=debug
